# Generated by Django 5.0.7 on 2026-06-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='recommended_courses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='recommended_courses',
            field=models.JSONField(default=list),
        ),
    ]
