# Generated by Django 5.0.7 on 2026-06-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_career_recommended_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_status',
            field=models.CharField(blank=True, choices=[('new', 'New to the system'), ('continuing', 'Continuing student')], max_length=20),
        ),
    ]
