# Generated by Django 5.0.7 on 2026-07-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_onboarding_completed_profile_study_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationhistory',
            name='favourite_subject',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='interest_area',
            field=models.CharField(max_length=80),
        ),
    ]
