# Generated by Django 5.0.7 on 2026-07-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recommendationhistory_favourite_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_goal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High school'), ('college', 'College'), ('university', 'University'), ('vocational', 'Vocational / technical'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_type',
            field=models.CharField(blank=True, choices=[('first_time_applicant', 'First-time applicant'), ('continuing_student', 'Continuing student'), ('high_school_student', 'High school student')], max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='support_note',
            field=models.TextField(blank=True),
        ),
    ]
