services:
  - type: web
    name: ai-career-path-recommender-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind=0.0.0.0:$PORT career_recommender.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_USE_SQLITE
        value: "False"
      - key: DB_SSL_REQUIRE
        value: "True"
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1,.vercel.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://ai-career-path-recommender-system.vercel.app,http://localhost:5173,http://127.0.0.1:5173"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://ai-career-path-recommender-system.vercel.app,http://localhost:5173,http://127.0.0.1:5173"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
